[package]
name = "notes-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.16.0"
serde = "1.0.132"
askama = "0.11.0"
surf = "2.3.2"
pulldown-cmark = "0.9.0"
dotenv = "0.15.0"
